// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIQAaL36yvyQWU00IADsxQeXHoXZgR5dk',
    appId: '1:624751968974:web:1710da272643718537869f',
    messagingSenderId: '624751968974',
    projectId: 'flash-chat-7a99b',
    authDomain: 'flash-chat-7a99b.firebaseapp.com',
    storageBucket: 'flash-chat-7a99b.appspot.com',
    measurementId: 'G-8DWYKR5TQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCR4zC6K03l54fBxoyKk_JrDTzrShXYE',
    appId: '1:624751968974:android:869beed381e12a8a37869f',
    messagingSenderId: '624751968974',
    projectId: 'flash-chat-7a99b',
    storageBucket: 'flash-chat-7a99b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj6UXYXvAXBU7ixrnKeyxXPvYnWktQYqc',
    appId: '1:624751968974:ios:2dc1459b6b23106037869f',
    messagingSenderId: '624751968974',
    projectId: 'flash-chat-7a99b',
    storageBucket: 'flash-chat-7a99b.appspot.com',
    iosBundleId: 'com.who.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj6UXYXvAXBU7ixrnKeyxXPvYnWktQYqc',
    appId: '1:624751968974:ios:43ef8ba34b56578a37869f',
    messagingSenderId: '624751968974',
    projectId: 'flash-chat-7a99b',
    storageBucket: 'flash-chat-7a99b.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIQAaL36yvyQWU00IADsxQeXHoXZgR5dk',
    appId: '1:624751968974:web:ef89c59588c9ed3337869f',
    messagingSenderId: '624751968974',
    projectId: 'flash-chat-7a99b',
    authDomain: 'flash-chat-7a99b.firebaseapp.com',
    storageBucket: 'flash-chat-7a99b.appspot.com',
    measurementId: 'G-1NBNFKXWHW',
  );
}
